services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-biotechcal}'
      - 'POSTGRES_USER=${POSTGRES_USER:-postgres}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
