CREATE TABLE company (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker  VARCHAR(255) NOT NULL UNIQUE,
    name    VARCHAR(255) NOT NULL,
    notes   VARCHAR(255)
);

CREATE TABLE catalyst (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalyst_type        VARCHAR(255) NOT NULL,
    expected_date_start  DATE,
    expected_date_end    DATE,
    drug_name            VARCHAR(255) NOT NULL,
    company_id           BIGINT REFERENCES company (id),
    notes                VARCHAR(255),
    source               VARCHAR(50)  NOT NULL DEFAULT 'MANUAL',
    external_id          VARCHAR(255)
);

CREATE INDEX idx_catalyst_company_id ON catalyst (company_id);
CREATE INDEX idx_catalyst_external_id ON catalyst (external_id);
